Librairies Loading

In [1]:
#Librairies
import pandas as pd
import numpy as np
import sklearn.cluster

Data Loading from yhe results of the clustering

In [2]:
mega_cluster_number=10

In [3]:
number_cluster=100

In [4]:
#dataframe with the rating and the cluster for each movies
dfratings=pd.read_csv('../data/dfratings_cluster.csv',index_col=False)

In [5]:
#dataframe with the genome and the cluster for each movies

genome_top=pd.read_csv('../data/genome_cluster.csv',header=1)

In [6]:
#numpy array with the centrer of the cluster coordinates and the cluster label
cluster_centroid=np.genfromtxt('../data/cluster_centroid.csv',delimiter=";")

In [7]:
cluster_centroid.shape


(100, 50)

In [8]:
#movies  qui donne la correspondance des titre des films, leur genre avec leur movieId, et un coefficient d'age
dfmovies=pd.read_csv("../data/dfmovies_coef_age.csv", sep=',', index_col="movieId")
display(dfmovies.info())
display(dfmovies.head(5))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27049 entries, 1 to 131262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   title     27049 non-null  object 
 1   genres    27049 non-null  object 
 2   year      27049 non-null  int64  
 3   coef_age  27049 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.0+ MB


None

title  \
movieId                                       
1                          Toy Story (1995)   
2                            Jumanji (1995)   
3                   Grumpier Old Men (1995)   
4                  Waiting to Exhale (1995)   
5        Father of the Bride Part II (1995)   

                                              genres  year  coef_age  
movieId                                                               
1        Adventure|Animation|Children|Comedy|Fantasy  1995   4.65396  
2                         Adventure|Children|Fantasy  1995   4.65396  
3                                     Comedy|Romance  1995   4.65396  
4                               Comedy|Drama|Romance  1995   4.65396  
5                                             Comedy  1995   4.65396

Check that the data loading is correct

In [9]:
dfratings.head()

Unnamed: 0  userId  movieId  rating   timestamp  cluster
0           0       1        2     3.5  1112486027     61.0
1           1       1       29     3.5  1112484676     18.0
2           2       1       32     3.5  1112484819     63.0
3           3       1       47     3.5  1112484727     16.0
4           4       1       50     3.5  1112484580     16.0

In [10]:
dfratings=dfratings.dropna()

In [11]:
#elimation de la ligne de NaN lié à la conversion en csv d'une double colonne
genome_top=genome_top.dropna()

genome_top.head()

In [12]:
genome_top=genome_top.rename(columns={"Unnamed: 51":"label"})

In [13]:
genome_top["tagId"]=genome_top["tagId"].astype(int)

In [14]:
genome_top["label"]=genome_top["label"].astype(int)

In [15]:
dfratings["cluster"]=dfratings["cluster"].astype(int)

In [16]:
genome_top["mega_label"]=genome_top["label"]

In [17]:
dfratings["mega_label"]=dfratings["cluster"]

In [18]:
print(cluster_centroid[:])

[[0.31682483 0.24096599 0.26061565 ... 0.22277211 0.22156122 0.19654252]
 [0.31752871 0.24348086 0.31135646 ... 0.25805622 0.25161005 0.25775837]
 [0.37591118 0.38839474 0.48938816 ... 0.33545724 0.35613487 0.33173684]
 ...
 [0.25322667 0.28042333 0.37575333 ... 0.25423667 0.37242333 0.34899333]
 [0.39371519 0.37125949 0.58545886 ... 0.36176899 0.54749684 0.64975949]
 [0.55225    0.72056148 0.39409016 ... 0.30782787 0.45778689 0.26842623]]


In [19]:
#creation of model clf ky Agglometrive Ward method with 10 clusters in order to obtain 10 mega cluster
clf = sklearn.cluster.AgglomerativeClustering(n_clusters = mega_cluster_number, affinity = 'euclidean', linkage = 'ward')

In [20]:
clf.fit(cluster_centroid)

AgglomerativeClustering(n_clusters=10)

In [21]:
print(clf.labels_)

[0 1 4 2 0 0 7 0 8 3 1 9 6 2 1 2 5 0 7 1 0 1 3 1 4 1 7 3 2 1 2 0 4 2 0 1 6
 7 2 1 5 0 2 0 0 1 1 6 4 8 6 1 0 1 6 4 0 5 9 4 0 0 0 5 0 1 1 2 1 6 8 0 8 5
 3 6 4 7 0 6 0 8 4 2 1 2 0 2 8 9 1 2 3 8 2 1 1 9 7 4]


In [22]:
print(len(clf.labels_))

100


In [23]:
print(clf.labels_[27])

3


In [25]:
dfratings["centroid"]=dfratings["cluster"]

for i in range(len(clf.labels_)) :
    genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
    dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
    #dfratings.centroid[dfratings["cluster"]==i]=cluster_centroid[i]


C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genome_top.mega_label[genome_top["label"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfratings.mega_label[dfratings["cluster"]==i]=clf.labels_[i]
C:\Users\celbo\AppData\Local\Temp\ipykernel_31312\4227973581.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

In [26]:
genome_top.head()

tagId       21       22      169     188      195      203      212  \
1      1  0.33025  0.28250  0.20525  0.4860  0.59000  0.92625  0.12350   
2      2  0.45100  0.60200  0.22825  0.4865  0.62600  0.87025  0.12975   
3      3  0.28000  0.20775  0.29950  0.4405  0.53800  0.34850  0.13750   
4      4  0.49875  0.44650  0.31100  0.4185  0.26125  0.24075  0.13425   
5      5  0.27575  0.21075  0.27050  0.5545  0.56800  0.39025  0.12300   

       220      240  ...     992      999     1008     1051     1064     1070  \
1  0.78025  0.35550  ...  0.4345  0.49000  0.60950  0.36300  0.42050  0.26150   
2  0.35625  0.11600  ...  0.1260  0.44075  0.14825  0.15050  0.22075  0.23475   
3  0.18975  0.23050  ...  0.4220  0.26675  0.21175  0.20725  0.21875  0.41825   
4  0.18825  0.13475  ...  0.1985  0.18425  0.17600  0.18325  0.28400  0.35950   
5  0.18025  0.21200  ...  0.3450  0.23850  0.18300  0.15025  0.21400  0.28475   

      1091     1104  label  mega_label  
1  0.41050  0.29925     67           2  
2  0.19125  0.31600     61           0  
3  0.21250  0.16800     71           0  
4  0.18575  0.17850     41           0  
5  0.18750  0.26975      5           0  

[5 rows x 53 columns]

In [27]:
dfratings.head()

Unnamed: 0  userId  movieId  rating   timestamp  cluster  mega_label  \
0           0       1        2     3.5  1112486027       61           0   
1           1       1       29     3.5  1112484676       18           7   
2           2       1       32     3.5  1112484819       63           5   
3           3       1       47     3.5  1112484727       16           5   
4           4       1       50     3.5  1112484580       16           5   

   centroid  
0        61  
1        18  
2        63  
3        16  
4        16

In [28]:
dfratings_by_movie=pd.DataFrame(dfratings.groupby("movieId").mean())



In [29]:
dfratings_by_movie.head()

Unnamed: 0        userId    rating     timestamp  cluster  \
movieId                                                                
1        1.003418e+07  69282.396821  3.921240  1.052654e+09     67.0   
2        1.001796e+07  69169.928202  3.211977  1.037616e+09     61.0   
3        1.000387e+07  69072.079388  3.151040  9.596480e+08     71.0   
4        1.008766e+07  69652.913280  2.861393  9.242144e+08     41.0   
5        1.000964e+07  69113.475454  3.064592  9.620161e+08      5.0   

         mega_label  centroid  
movieId                        
1               2.0      67.0  
2               0.0      61.0  
3               0.0      71.0  
4               0.0      41.0  
5               0.0       5.0

In [30]:
popularity=dfratings.groupby("movieId").count()
popularity.head()

Unnamed: 0  userId  rating  timestamp  cluster  mega_label  centroid
movieId                                                                      
1             49695   49695   49695      49695    49695       49695     49695
2             22243   22243   22243      22243    22243       22243     22243
3             12735   12735   12735      12735    12735       12735     12735
4              2756    2756    2756       2756     2756        2756      2756
5             12161   12161   12161      12161    12161       12161     12161

In [31]:
dfratings_by_movie["popularity"]=popularity["userId"]
dfratings_by_movie=dfratings_by_movie.drop(["Unnamed: 0", "userId", "timestamp"], axis=1)

In [32]:
dfratings_by_movie.head()

rating  cluster  mega_label  centroid  popularity
movieId                                                     
1        3.921240     67.0         2.0      67.0       49695
2        3.211977     61.0         0.0      61.0       22243
3        3.151040     71.0         0.0      71.0       12735
4        2.861393     41.0         0.0      41.0        2756
5        3.064592      5.0         0.0       5.0       12161

In [33]:
dfratings_by_movie=dfratings_by_movie.merge(right=dfmovies,on='movieId',how='left')


In [36]:
dfratings_by_movie=dfratings_by_movie.drop(["genres", "year"], axis=1)
dfratings_by_movie.head()


KeyError: "['genres', 'year'] not found in axis"

In [37]:
dfratings_by_movie["coef_age"]=dfratings_by_movie["rating"]+20*dfratings_by_movie["coef_age"]

In [38]:
dfratings_by_movie.to_csv("../data/mega_cluster_by_movie.csv")

In [ ]:
recom_base=[]



for i in range(mega_cluster_number) :
    print(i)
    print(dfratings[dfratings["mega_label"]==i].groupby("movieId").count().sort_values('rating',ascending=False).head(1).index.values)
    recom_base.append(dfratings[dfratings["mega_label"]==i].groupby("movieId").count().sort_values('rating',ascending=False).head(1).index.values)
    
print(recom_base)




In [ ]:
genome_top.loc[296]


In [ ]:
recom_base_title=[]


for i in recom_base :
    recom_base_title.append(dfmovies.loc[i].title)

    
print(recom_base_title)



L'utilisateur choisit un film

In [ ]:
chosen_movie=296

In [ ]:
chosen_mega_cluster=genome_top[genome_top["tagId"]==chosen_movie].mega_label.values[0]

In [ ]:
print(chosen_mega_cluster)

In [ ]:
i=0
print(dfratings[dfratings["mega_label"]==chosen_mega_cluster].groupby("movieId").count().sort_values('rating',ascending=False).head(1).index.values)


In [ ]:
recom_second=[]

small_cluster_per_mega=number_cluster//mega_cluster_number

small_clusters=pd.unique(dfratings[dfratings["mega_label"]==chosen_mega_cluster].cluster.values)

for i in small_clusters :
    print(i)
    print(dfratings[(dfratings["mega_label"]==chosen_mega_cluster) & (dfratings["cluster"]==i)].groupby("movieId").count().sort_values('rating',ascending=False).head(1).index.values)
    recom_second.append(dfratings[(dfratings["mega_label"]==chosen_mega_cluster) & (dfratings["cluster"]==i)].groupby("movieId").count().sort_values('rating',ascending=False).head(1).index.values)
    
print(recom_second)    

In [ ]:
recom_second_title=[]


for i in recom_second :
    recom_second_title.append(dfmovies.loc[i].title)

    
print(recom_second_title)

In [ ]:
dfratings[(dfratings["mega_label"]==chosen_mega_cluster) & (dfratings["cluster"]==small_clusters[0])].groupby("movieId").agg(['count']).head(10).sort_values('count',ascending=False)